TIMEOUT = "300"

# Browser
DEFAULT_BROWSER = "firefox"
WINDOW_WEIGHT = "1920"
WINDOW_HEIGHT = "1080"

# Cypress qa url
CYPRESS_QA_URL = "http://bo.cqgame.qa"

# Cypress qa user
ADMIN_USER = "adminqa"
GENERAL_AGENT_USER = "qa5566"
AGENT_USER = "qEmma"
ADMIN_USER_PASSWORD = "cy5566"
GENERAL_AGENT_USER_PASSWORD = "iLoveCQ9"
AGENT_USER_PASSWORD = "aaaa1234"