TIMEOUT = "300"

# Browser
DEFAULT_BROWSER = "firefox"
WINDOW_WEIGHT = "1920"
WINDOW_HEIGHT = "1080"

# Cypress qa url
CYPRESS_QA_URL = "http://bo.cqgame.qa"

# Cypress qa user
ADMIN_USER = "adminqa"
GENERAL_AGENT_USER = "qtest20170830"
AGENT_USER = "qEmma"
ADMIN_USER_PASSWORD = "cy5566"
GENERAL_AGENT_USER_PASSWORD = "aaaa1234"
AGENT_USER_PASSWORD = "aaaa1234"

#Cypress qa user token
AGENT_SYS_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOiI1OTliZjZmZDU0MDBiMDAwMDE0MjlhNmYiLCJhY2NvdW50IjoicUVtbWEiLCJvd25lciI6IjU5NGNiNjk4OThjNGExMDAwMTFkMDBiYSIsInBhcmVudCI6IjU5NGNiNjk4OThjNGExMDAwMTFkMDBiYSIsImN1cnJlbmN5IjoiQ05ZIiwianRpIjoiMjc1NDM4ODM3IiwiaWF0IjoxNTAzMzkzNTMzLCJpc3MiOiJDeXByZXNzIiwic3ViIjoiU1NUb2tlbiJ9.Qj72m6-DmXQ1D8knQvJzQN-QSDJXT-INtxqIYP2Jj_Q"

#Cypress qa api url
CYPRESS_QA_API_URL = "http://api.cqgame.qa"